// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa4zn641hYZQC54XfZoukg4uZ6piniyyI',
    appId: '1:422350596792:web:8d2b21416c480e70ad624d',
    messagingSenderId: '422350596792',
    projectId: 'test-flutter-5b3ef',
    authDomain: 'test-flutter-5b3ef.firebaseapp.com',
    storageBucket: 'test-flutter-5b3ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWx0rJfy5rFtujwAqTDwg6SoBLkZEzzv4',
    appId: '1:422350596792:android:457fd1f589d90c09ad624d',
    messagingSenderId: '422350596792',
    projectId: 'test-flutter-5b3ef',
    storageBucket: 'test-flutter-5b3ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGoaZvAQWElz170GJtfi-oOVvIlXP3xF4',
    appId: '1:422350596792:ios:c79a81798cc89149ad624d',
    messagingSenderId: '422350596792',
    projectId: 'test-flutter-5b3ef',
    storageBucket: 'test-flutter-5b3ef.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGoaZvAQWElz170GJtfi-oOVvIlXP3xF4',
    appId: '1:422350596792:ios:c79a81798cc89149ad624d',
    messagingSenderId: '422350596792',
    projectId: 'test-flutter-5b3ef',
    storageBucket: 'test-flutter-5b3ef.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa4zn641hYZQC54XfZoukg4uZ6piniyyI',
    appId: '1:422350596792:web:9cc97e32a29db26ead624d',
    messagingSenderId: '422350596792',
    projectId: 'test-flutter-5b3ef',
    authDomain: 'test-flutter-5b3ef.firebaseapp.com',
    storageBucket: 'test-flutter-5b3ef.firebasestorage.app',
  );
}
