// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-R_5oawGlNoKHsrh_OqBmMhvHk38ZVVY',
    appId: '1:105456700735:web:abc2b2185f622bed11578a',
    messagingSenderId: '105456700735',
    projectId: 'test-login-a79ff',
    authDomain: 'test-login-a79ff.firebaseapp.com',
    storageBucket: 'test-login-a79ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWkpOGe2u6_FeCyg4Jf-9aGQ87mAkLSAs',
    appId: '1:105456700735:android:01929f5f335fa39811578a',
    messagingSenderId: '105456700735',
    projectId: 'test-login-a79ff',
    storageBucket: 'test-login-a79ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt89wnZOCWtYHe86-XxaM7l4E304PoiQY',
    appId: '1:105456700735:ios:3e89d9c8b7fef3e211578a',
    messagingSenderId: '105456700735',
    projectId: 'test-login-a79ff',
    storageBucket: 'test-login-a79ff.firebasestorage.app',
    iosBundleId: 'com.example.actividadNotificaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt89wnZOCWtYHe86-XxaM7l4E304PoiQY',
    appId: '1:105456700735:ios:3e89d9c8b7fef3e211578a',
    messagingSenderId: '105456700735',
    projectId: 'test-login-a79ff',
    storageBucket: 'test-login-a79ff.firebasestorage.app',
    iosBundleId: 'com.example.actividadNotificaciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-R_5oawGlNoKHsrh_OqBmMhvHk38ZVVY',
    appId: '1:105456700735:web:65b405684f8ff71b11578a',
    messagingSenderId: '105456700735',
    projectId: 'test-login-a79ff',
    authDomain: 'test-login-a79ff.firebaseapp.com',
    storageBucket: 'test-login-a79ff.firebasestorage.app',
  );
}
